//
// Autogenerated by Satish Babariya 
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {

    /// Base translation: OK
    public static var ok : String = NSLocalizedString("ok", comment: "")

    /// Base translation: Set number of images in one request.
    public static var themesdetails : String = NSLocalizedString("themesdetails", comment: "")

    /// Base translation: User is throttled, try again later
    public static var useristhrottled : String = NSLocalizedString("useristhrottled", comment: "")

    /// Base translation: Set imageboard service settings
    public static var servicesettingsdetails : String = NSLocalizedString("servicesettingsdetails", comment: "")

    /// Base translation: User Throttled
    public static var userthrottled : String = NSLocalizedString("userthrottled", comment: "")

    /// Base translation: Already Exists
    public static var alreadyexist : String = NSLocalizedString("alreadyexist", comment: "")

    /// Base translation: Enter Number
    public static var textbulletinplaceholder : String = NSLocalizedString("textbulletinplaceholder", comment: "")

    /// Base translation: Layout
    public static var layout : String = NSLocalizedString("layout", comment: "")

    /// Base translation: Internal error, Please try again after sometime.
    public static var decodererror : String = NSLocalizedString("decodererror", comment: "")

    /// Base translation: Unauthorized
    public static var unauthorized : String = NSLocalizedString("unauthorized", comment: "")

    /// Base translation: Bad Request
    public static var badrequest : String = NSLocalizedString("badrequest", comment: "")

    /// Base translation: Services Settings
    public static var servicesettings : String = NSLocalizedString("servicesettings", comment: "")

    /// Base translation: A database timeout, or some unknown error occurred on the server
    public static var adatabasetimeout : String = NSLocalizedString("adatabasetimeout", comment: "")

    /// Base translation: Kochan
    public static var Kochan : String = NSLocalizedString("Kochan", comment: "")

    /// Base translation: Not Found
    public static var notfound : String = NSLocalizedString("notfound", comment: "")

    /// Base translation: e.g. https://example.com
    public static var domaindetails : String = NSLocalizedString("domaindetails", comment: "")

    /// Base translation: Danbooru
    public static var Danbooru : String = NSLocalizedString("Danbooru", comment: "")

    /// Base translation: Locked
    public static var locked : String = NSLocalizedString("locked", comment: "")

    /// Base translation: In Home screen this change will effect after next app launch. 
    public static var textbulletindescription2 : String = NSLocalizedString("textbulletindescription2", comment: "")

    /// Base translation: Flickr
    public static var Flickr : String = NSLocalizedString("Flickr", comment: "")

    /// Base translation: Set number of images in one request.
    public static var noofimagesdetails : String = NSLocalizedString("noofimagesdetails", comment: "")

    /// Base translation: About Danbooru Lite
    public static var about : String = NSLocalizedString("about", comment: "")

    /// Base translation: The given parameters could not be parsed
    public static var thegivanparamcouldnot : String = NSLocalizedString("thegivanparamcouldnot", comment: "")

    /// Base translation: Authentication failed
    public static var authendicationfailed : String = NSLocalizedString("authendicationfailed", comment: "")

    /// Base translation: Settings
    public static var settings : String = NSLocalizedString("settings", comment: "")

    /// Base translation: High
    public static var high : String = NSLocalizedString("high", comment: "")

    /// Base translation: Gone
    public static var gone : String = NSLocalizedString("gone", comment: "")

    /// Base translation: Internal Server Error
    public static var internalservererror : String = NSLocalizedString("internalservererror", comment: "")

    /// Base translation: Skip
    public static var skip : String = NSLocalizedString("skip", comment: "")

    /// Base translation: Forbidden
    public static var forbidden : String = NSLocalizedString("forbidden", comment: "")

    /// Base translation: Setup URL
    public static var setupurl : String = NSLocalizedString("setupurl", comment: "")

    /// Base translation: You must enter some number to continue.
    public static var texterror : String = NSLocalizedString("texterror", comment: "")

    /// Base translation: Record could not be saved
    public static var recordcouldnot : String = NSLocalizedString("recordcouldnot", comment: "")

    /// Base translation: Change
    public static var change : String = NSLocalizedString("change", comment: "")

    /// Base translation: Yande.re
    public static var Yandere : String = NSLocalizedString("Yandere", comment: "")

    /// Base translation: Number of Images in one Request
    public static var textbulletintitle : String = NSLocalizedString("textbulletintitle", comment: "")

    /// Base translation: Request was successful
    public static var reqyestwassucess : String = NSLocalizedString("reqyestwassucess", comment: "")

    /// Base translation: Server Error
    public static var serverError : String = NSLocalizedString("serverError", comment: "")

    /// Base translation: Themes
    public static var themes : String = NSLocalizedString("themes", comment: "")

    /// Base translation: Invalid Parameters
    public static var invalidparam : String = NSLocalizedString("invalidparam", comment: "")

    /// Base translation: The given parameters were invalid
    public static var thgivenparamerer : String = NSLocalizedString("thgivenparamerer", comment: "")

    /// Base translation: Set number of images in one single row.
    public static var imagesinrowdetails : String = NSLocalizedString("imagesinrowdetails", comment: "")

    /// Base translation: Select Theme Color
    public static var selectcolor : String = NSLocalizedString("selectcolor", comment: "")

    /// Base translation: Low
    public static var low : String = NSLocalizedString("low", comment: "")

    /// Base translation: Server cannot currently handle the request, try again later (returned during downbooru)
    public static var servercannot : String = NSLocalizedString("servercannot", comment: "")

    /// Base translation: Number of Images in one Row
    public static var textbulletintitle2 : String = NSLocalizedString("textbulletintitle2", comment: "")

    /// Base translation: No Content
    public static var nocontent : String = NSLocalizedString("nocontent", comment: "")

    /// Base translation: Danbooru
    public static var home : String = NSLocalizedString("home", comment: "")

    /// Base translation: https://
    public static var domaintext : String = NSLocalizedString("domaintext", comment: "")

    /// Base translation: Gelbooru
    public static var Gelbooru : String = NSLocalizedString("Gelbooru", comment: "")

    /// Base translation: Service URL
    public static var domainplaceholder : String = NSLocalizedString("domainplaceholder", comment: "")

    /// Base translation: Url is not valid.
    public static var urlnotvalid : String = NSLocalizedString("urlnotvalid", comment: "")

    /// Base translation: Application
    public static var application : String = NSLocalizedString("application", comment: "")

    /// Base translation: Remove cached images form device.
    public static var clearcachedetails : String = NSLocalizedString("clearcachedetails", comment: "")

    /// Base translation: Next
    public static var next : String = NSLocalizedString("next", comment: "")

    /// Base translation: Danbooru Lite
    public static var appname : String = NSLocalizedString("appname", comment: "")

    /// Base translation: Services
    public static var services : String = NSLocalizedString("services", comment: "")

    /// Base translation: This change will reflact immediately
    public static var textbulletindescription : String = NSLocalizedString("textbulletindescription", comment: "")

    /// Base translation: Pagination limit
    public static var paginationliit : String = NSLocalizedString("paginationliit", comment: "")

    /// Base translation: Cancel
    public static var cancel : String = NSLocalizedString("cancel", comment: "")

    /// Base translation: Resource already exists
    public static var resourcealreadyexist : String = NSLocalizedString("resourcealreadyexist", comment: "")

    /// Base translation: Thumbnail Quality
    public static var thumbnailquality : String = NSLocalizedString("thumbnailquality", comment: "")

    /// Base translation: No. of Images in one Page
    public static var noofimages : String = NSLocalizedString("noofimages", comment: "")

    /// Base translation: Clear Image Cache
    public static var clearcache : String = NSLocalizedString("clearcache", comment: "")

    /// Base translation: Service Unavailable
    public static var serviceunailable : String = NSLocalizedString("serviceunailable", comment: "")

    /// Base translation: No Internet Connection
    public static var nointernet : String = NSLocalizedString("nointernet", comment: "")

    /// Base translation: No. of Images in one Row
    public static var imagesinrow : String = NSLocalizedString("imagesinrow", comment: "")

    /// Base translation: The resource is locked and cannot be modified
    public static var resourceislocke : String = NSLocalizedString("resourceislocke", comment: "")

    /// Base translation: Service Setup
    public static var service : String = NSLocalizedString("service", comment: "")

    /// Base translation: Privacy Policy
    public static var privacy : String = NSLocalizedString("privacy", comment: "")

    /// Base translation: Access denied
    public static var acessdenid : String = NSLocalizedString("acessdenid", comment: "")

    /// Base translation: Invalid Record
    public static var invalidrecord : String = NSLocalizedString("invalidrecord", comment: "")

}